-- --senha: D7e-kx;$7wQD5e
-- insert into db_users (id, email, password, role, username)
-- values (default,
--         'jesse.haniel@ada.tech',
--         '$2a$10$Z7pZX/j7CXN9bfMe3GVXx.2F7Jrb2nMgod9QwFVwQwzsmN0mdGDju',
--         'ADMIN',
--         'jesse.haniel');
--
-- -- senha: abc123456$R
-- insert into db_users (id, email, password, role, username)
-- values (default,
--         'marcos@ramiro.com',
--         '$2a$10$6XSRSHyMmC3AXxUFEWkkJOz9uJQiLsPIUhQsQM0bqxRnoRVcWtghO',
--         'CLIENT',
--         'marcos.ramiro');
select * from db_users